print('Este programa irá mostrar todas as características do que foi digitado.')
algo = input('Digite algo')
print('O tipo primitivo dessa classe é {}'.format(type(algo)))
print('Tem espaços? {}'.format(algo.isspace()))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print('É alfanúmerico? {}'.format(algo.isalnum()))
print('Está em maiúsculas? {}'.format(algo.isupper()))
print('Está em minúsculas? {}'.format(algo.islower()))
print('Está capitalizada? {}'.format(algo.isprintable()))